name: Deploy

on:
  push:
    branches:
      - 'production'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: touch .env
      - run: npm run build
        env:
          CI: true

      - name: Build & Publish docker images
        run: |
          docker build -t docker.dev.tolgee.io/documentation:latest -f docker/Dockerfile .
          docker login docker.dev.tolgee.io -u github -p $DOCKER_REGISTRY_PASSWORD
          docker tag docker.dev.tolgee.io/documentation:latest docker.dev.tolgee.io/documentation:production
          docker push --all-tags docker.dev.tolgee.io/documentation
        env:
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Deploy
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBERNETES_SERVICE_CONFIG }}
          KUBECTL_VERSION: "1.19"
        with:
          args: '"rollout restart deployment/tolgee-documentation-deployment"'